[package]
name = "airdrop"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
airdrop_deployer="0xacff8ae34d6d2e2d879e47599b7a6b8738429ff7015a664c087f81e0cb36ceaf"


[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
subdir = 'aptos-move/framework/supra-framework'
rev = 'aptosvm-v1.16_supra-v1.2.3'

[dev-dependencies]

[dependencies]
core = { local ="../supra-vrf/core" }
SupraVrf = { local = "../supra-vrf/testnet"  }
Coin = { local = "../token_call"  }
TOKEN2 = { local = "../token2_call"  }
TOKEN3 = { local = "../token3_call"  }
TOKEN4 = { local = "../token4_call"  }
